---
common_packages:
  - vim
  - curl
  - wget
  - git
  - jq
  - tcpdump
  - net-tools
  - dnsutils
  - mtr-tiny
  - iotop
  - sysstat
  - lsof
  - strace
  - btop
  - tree
  - unzip
  - rsync
  - ca-certificates
  - gnupg
  - apt-transport-https
  - software-properties-common

packages_to_remove:
  - htop
