[debian_vms]
# Ajouter vos VMs ici
# vm1.example.com
# vm2.example.com

[debian_vms:vars]
ansible_user=ansible
ansible_port=22
# Après masterisation, changer en:
# ansible_port=1822
centreon_poller=10.0.0.100
